-- IAM
CREATE TABLE IF NOT EXISTS iam.roles (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, description TEXT, is_system BOOLEAN DEFAULT false, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS iam.permissions (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(100) UNIQUE NOT NULL, module VARCHAR(50), action VARCHAR(50), resource VARCHAR(100), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS iam.user_roles (user_id VARCHAR(36) REFERENCES iam.users(id), role_id VARCHAR(36) REFERENCES iam.roles(id), PRIMARY KEY(user_id, role_id));
CREATE TABLE IF NOT EXISTS iam.role_permissions (role_id VARCHAR(36) REFERENCES iam.roles(id), permission_id VARCHAR(36) REFERENCES iam.permissions(id), PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS iam.sessions (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) REFERENCES iam.users(id), token VARCHAR(500) NOT NULL, ip_address VARCHAR(50), user_agent VARCHAR(500), expires_at TIMESTAMP NOT NULL, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS iam.policies (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, description TEXT, effect VARCHAR(10) DEFAULT 'allow', conditions JSONB NOT NULL, resource VARCHAR(200), action VARCHAR(50), priority INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());

-- WORKFLOW
CREATE TABLE IF NOT EXISTS workflow.definitions (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) NOT NULL, module VARCHAR(50), steps JSONB NOT NULL, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS workflow.instances (id VARCHAR(36) PRIMARY KEY, definition_id VARCHAR(36) REFERENCES workflow.definitions(id), entity_type VARCHAR(100), entity_id VARCHAR(36), current_step INTEGER DEFAULT 0, status VARCHAR(20) DEFAULT 'pending', initiated_by VARCHAR(36), data JSONB DEFAULT '{}', tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS workflow.steps (id VARCHAR(36) PRIMARY KEY, instance_id VARCHAR(36) REFERENCES workflow.instances(id), step_number INTEGER, approver_id VARCHAR(36), status VARCHAR(20) DEFAULT 'pending', comments TEXT, acted_at TIMESTAMP, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS workflow.approval_matrix (id VARCHAR(36) PRIMARY KEY, module VARCHAR(50), document_type VARCHAR(50), conditions JSONB, approvers JSONB NOT NULL, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());

-- AUDIT
CREATE TABLE IF NOT EXISTS audit.logs (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36), action VARCHAR(50) NOT NULL, module VARCHAR(50), entity_type VARCHAR(100), entity_id VARCHAR(36), old_values JSONB, new_values JSONB, ip_address VARCHAR(50), user_agent VARCHAR(500), extra_data JSONB, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());

-- MASTER
CREATE TABLE IF NOT EXISTS master.organizations (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, type VARCHAR(50), parent_id VARCHAR(36), address JSONB, contact JSONB, settings JSONB DEFAULT '{}', is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS master.departments (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) NOT NULL, org_id VARCHAR(36), parent_id VARCHAR(36), head_id VARCHAR(36), is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS master.locations (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(50), address JSONB, geo JSONB, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS master.currencies (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(10) UNIQUE NOT NULL, symbol VARCHAR(5), exchange_rate DECIMAL(18,6) DEFAULT 1, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS master.uom (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(20) UNIQUE NOT NULL, category VARCHAR(50), base_uom VARCHAR(20), conversion_factor DECIMAL(18,6) DEFAULT 1, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS master.items (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, category VARCHAR(100), type VARCHAR(50), uom_id VARCHAR(36), description TEXT, specs JSONB DEFAULT '{}', is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS master.vendors (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, type VARCHAR(50), contact JSONB, address JSONB, payment_terms VARCHAR(100), is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS master.customers (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, type VARCHAR(50), contact JSONB, address JSONB, credit_limit DECIMAL(18,2), payment_terms VARCHAR(100), is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));

-- INVENTORY
CREATE TABLE IF NOT EXISTS inventory.stock (id VARCHAR(36) PRIMARY KEY, item_id VARCHAR(36) NOT NULL, location_id VARCHAR(36), warehouse_id VARCHAR(36), batch_no VARCHAR(50), serial_no VARCHAR(50), qty DECIMAL(18,4) DEFAULT 0, reserved_qty DECIMAL(18,4) DEFAULT 0, uom VARCHAR(20), unit_cost DECIMAL(18,4), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS inventory.movements (id VARCHAR(36) PRIMARY KEY, item_id VARCHAR(36) NOT NULL, from_location VARCHAR(36), to_location VARCHAR(36), qty DECIMAL(18,4) NOT NULL, type VARCHAR(50) NOT NULL, reference_type VARCHAR(50), reference_id VARCHAR(36), batch_no VARCHAR(50), remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS inventory.adjustments (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, location_id VARCHAR(36), reason VARCHAR(200), status VARCHAR(20) DEFAULT 'draft', lines JSONB, approved_by VARCHAR(36), approved_at TIMESTAMP, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));

-- PROCUREMENT
CREATE TABLE IF NOT EXISTS procurement.purchase_requests (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, requester_id VARCHAR(36), department_id VARCHAR(36), priority VARCHAR(20) DEFAULT 'normal', status VARCHAR(20) DEFAULT 'draft', lines JSONB, remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS procurement.purchase_orders (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, vendor_id VARCHAR(36) NOT NULL, pr_id VARCHAR(36), status VARCHAR(20) DEFAULT 'draft', lines JSONB, subtotal DECIMAL(18,2), tax DECIMAL(18,2), total DECIMAL(18,2), currency VARCHAR(10) DEFAULT 'INR', payment_terms VARCHAR(100), delivery_date DATE, remarks TEXT, approved_by VARCHAR(36), approved_at TIMESTAMP, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS procurement.grn (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, po_id VARCHAR(36) REFERENCES procurement.purchase_orders(id), vendor_id VARCHAR(36), status VARCHAR(20) DEFAULT 'draft', lines JSONB, remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));

-- FINANCE
CREATE TABLE IF NOT EXISTS finance.accounts (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, type VARCHAR(50) NOT NULL, parent_id VARCHAR(36), currency VARCHAR(10) DEFAULT 'INR', is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS finance.journal_entries (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, type VARCHAR(50), narration TEXT, status VARCHAR(20) DEFAULT 'draft', lines JSONB, total_debit DECIMAL(18,2), total_credit DECIMAL(18,2), approved_by VARCHAR(36), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS finance.invoices (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, type VARCHAR(20) NOT NULL, party_id VARCHAR(36), party_type VARCHAR(20), status VARCHAR(20) DEFAULT 'draft', lines JSONB, subtotal DECIMAL(18,2), tax DECIMAL(18,2), total DECIMAL(18,2), paid DECIMAL(18,2) DEFAULT 0, balance DECIMAL(18,2), due_date DATE, currency VARCHAR(10) DEFAULT 'INR', tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS finance.payments (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, type VARCHAR(20), party_id VARCHAR(36), party_type VARCHAR(20), amount DECIMAL(18,2) NOT NULL, method VARCHAR(50), reference VARCHAR(100), invoice_id VARCHAR(36), status VARCHAR(20) DEFAULT 'draft', tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));

-- MANUFACTURING
CREATE TABLE IF NOT EXISTS manufacturing.bom (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, product_id VARCHAR(36) NOT NULL, version_no INTEGER DEFAULT 1, status VARCHAR(20) DEFAULT 'draft', lines JSONB, routing JSONB, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS manufacturing.work_orders (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, product_id VARCHAR(36) NOT NULL, bom_id VARCHAR(36) REFERENCES manufacturing.bom(id), qty DECIMAL(18,4) NOT NULL, produced_qty DECIMAL(18,4) DEFAULT 0, status VARCHAR(20) DEFAULT 'planned', priority VARCHAR(20) DEFAULT 'normal', start_date DATE, end_date DATE, work_center VARCHAR(100), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS manufacturing.production_logs (id VARCHAR(36) PRIMARY KEY, work_order_id VARCHAR(36) REFERENCES manufacturing.work_orders(id), date DATE NOT NULL, qty_produced DECIMAL(18,4), qty_rejected DECIMAL(18,4) DEFAULT 0, operator_id VARCHAR(36), shift VARCHAR(20), remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());

-- QUALITY
CREATE TABLE IF NOT EXISTS quality.inspections (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, type VARCHAR(50), reference_type VARCHAR(50), reference_id VARCHAR(36), item_id VARCHAR(36), qty_inspected DECIMAL(18,4), qty_accepted DECIMAL(18,4), qty_rejected DECIMAL(18,4), status VARCHAR(20) DEFAULT 'pending', inspector_id VARCHAR(36), parameters JSONB, remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS quality.ncr (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, type VARCHAR(50), source VARCHAR(50), item_id VARCHAR(36), description TEXT, root_cause TEXT, corrective_action TEXT, status VARCHAR(20) DEFAULT 'open', severity VARCHAR(20), assigned_to VARCHAR(36), closed_at TIMESTAMP, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));

-- WAREHOUSE
CREATE TABLE IF NOT EXISTS warehouse.warehouses (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, location_id VARCHAR(36), type VARCHAR(50), capacity JSONB, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS warehouse.zones (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, warehouse_id VARCHAR(36) REFERENCES warehouse.warehouses(id), type VARCHAR(50), capacity JSONB, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS warehouse.bins (id VARCHAR(36) PRIMARY KEY, code VARCHAR(50) NOT NULL, zone_id VARCHAR(36) REFERENCES warehouse.zones(id), rack VARCHAR(20), shelf VARCHAR(20), position VARCHAR(20), capacity DECIMAL(18,4), is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS warehouse.transfers (id VARCHAR(36) PRIMARY KEY, doc_no VARCHAR(50) UNIQUE NOT NULL, date DATE NOT NULL, from_warehouse VARCHAR(36), to_warehouse VARCHAR(36), status VARCHAR(20) DEFAULT 'draft', lines JSONB, remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));

-- PROJECT
CREATE TABLE IF NOT EXISTS project.projects (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, description TEXT, manager_id VARCHAR(36), department_id VARCHAR(36), status VARCHAR(20) DEFAULT 'planning', priority VARCHAR(20) DEFAULT 'normal', start_date DATE, end_date DATE, budget DECIMAL(18,2), actual_cost DECIMAL(18,2) DEFAULT 0, progress INTEGER DEFAULT 0, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS project.tasks (id VARCHAR(36) PRIMARY KEY, project_id VARCHAR(36) REFERENCES project.projects(id), name VARCHAR(200) NOT NULL, description TEXT, assignee_id VARCHAR(36), status VARCHAR(20) DEFAULT 'todo', priority VARCHAR(20) DEFAULT 'normal', start_date DATE, due_date DATE, estimated_hours DECIMAL(8,2), actual_hours DECIMAL(8,2) DEFAULT 0, parent_id VARCHAR(36), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS project.timesheets (id VARCHAR(36) PRIMARY KEY, project_id VARCHAR(36) REFERENCES project.projects(id), task_id VARCHAR(36) REFERENCES project.tasks(id), user_id VARCHAR(36) NOT NULL, date DATE NOT NULL, hours DECIMAL(8,2) NOT NULL, description TEXT, status VARCHAR(20) DEFAULT 'draft', tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());

-- HR
CREATE TABLE IF NOT EXISTS hr.employees (id VARCHAR(36) PRIMARY KEY, emp_code VARCHAR(50) UNIQUE NOT NULL, user_id VARCHAR(36), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100), email VARCHAR(200), phone VARCHAR(20), department_id VARCHAR(36), designation VARCHAR(100), manager_id VARCHAR(36), date_of_joining DATE, date_of_birth DATE, gender VARCHAR(10), status VARCHAR(20) DEFAULT 'active', address JSONB, bank_details JSONB, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36), updated_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS hr.attendance (id VARCHAR(36) PRIMARY KEY, employee_id VARCHAR(36) REFERENCES hr.employees(id), date DATE NOT NULL, check_in TIMESTAMP, check_out TIMESTAMP, status VARCHAR(20) DEFAULT 'present', hours_worked DECIMAL(5,2), remarks TEXT, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr.leaves (id VARCHAR(36) PRIMARY KEY, employee_id VARCHAR(36) REFERENCES hr.employees(id), type VARCHAR(50) NOT NULL, from_date DATE NOT NULL, to_date DATE NOT NULL, days DECIMAL(4,1), reason TEXT, status VARCHAR(20) DEFAULT 'pending', approved_by VARCHAR(36), tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr.payroll (id VARCHAR(36) PRIMARY KEY, employee_id VARCHAR(36) REFERENCES hr.employees(id), month VARCHAR(7) NOT NULL, basic DECIMAL(18,2), allowances JSONB, deductions JSONB, gross DECIMAL(18,2), net DECIMAL(18,2), status VARCHAR(20) DEFAULT 'draft', paid_at TIMESTAMP, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());

-- ANALYTICS
CREATE TABLE IF NOT EXISTS analytics.reports (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, module VARCHAR(50), type VARCHAR(50), query TEXT, parameters JSONB, schedule JSONB, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));
CREATE TABLE IF NOT EXISTS analytics.dashboards (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL, layout JSONB, widgets JSONB, is_default BOOLEAN DEFAULT false, is_active BOOLEAN DEFAULT true, tenant_id VARCHAR(36) NOT NULL, is_deleted BOOLEAN DEFAULT false, version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), created_by VARCHAR(36));
